server:
  port: 8888

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://1.116.239.178:3306/course
    username: root
    password: root@123

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*

